public class AppsNetworksSummary {
	public Integer totalSocialNetworks { get; set; }
	public Integer totalSearchResults { get; set; }
	public Integer totalSocialMediaPosts { get; set; }
	public Decimal followerToFollowingRatio { get; set; }
	public Boolean hasFacebook { get; set; }
	public Boolean hasTwitter { get; set; }
	public Boolean hasLinkedIn { get; set; }
	public Boolean hasInstagram { get; set; }
	public Boolean hasOLX { get; set; }
	public Boolean hasMercadoLivre { get; set; }
}