/**
 * @description       :
 * @author            : Hersilio Belini de Oliveira
 * @group             :
 * @last modified on  : 2024-12-12
 * @last modified by  : Hersilio Belini de Oliveira
 * Modifications Log
 * Ver   Date         Author                        Modification
 * 1.0   2021-02-26   Hersilio Belini de Oliveira   Initial Version
**/
public enum MehtodRequestEnum {
    POST,
    GET,
    PUT
}